---
# tasks file for roles/db
- ansible.builtin.include_vars:
    ../../../environments/{{ env }}/group_vars/db.yml

#### Create and Configure Database
- name: Create a new database
  community.mysql.mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create database user with all privileges for database
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{mysql_pass}}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Check if database exists
  shell: mysql -e 'SHOW DATABASES;'
  register: db_result

- debug:
    var: db_result.stdout_lines

- name: Change my.cnf
  ansible.builtin.blockinfile:
    path: /etc/mysql/my.cnf
    block: |
      [mysqld]
      bind-address = 0.0.0.0

- name: Restart mysqld service
  ansible.builtin.systemd:
    name: mariadb
    state: restarted

- name: Get db listen on address
  shell: ss -ntpl |grep 3306
  register: listen_on

- debug:
    var: listen_on.stdout_lines
