---

- name: Install Database
  hosts: db
  become: true
  gather_facts: false
  roles:
    - db

- name: Deploy application
  hosts: web
  gather_facts: false
  roles:
    - {role: app, become: true}
    - {role: flask_app_install}
